##**NumPy Arrays / Matrices**

In [37]:
#Imports
import numpy as np
import time

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr) # Creating a 2D Array

[[1 2 3]
 [4 5 6]]


In [39]:
arr = np.zeros((3,4))
print(arr) # Printing a 3x4 Zero Matrix

arr1 = np.ones((2,3))
print(arr1) # Printing a 2x3 One Matrix

arr2 = np.eye(3)
print(arr2) # Prints a 3x3 Identity Matrix

arr3 = np.arange(12,20)
print(arr3) # Printing numbers in a range

arr4 = np.linspace(1,10,10)
print(arr4) # Prints evenly spaced values from 1 to 10

arr5 = np.random.randint(1, 100, 10)
print(arr5) # Generates 10 random numbers from 1 to 99

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[13 86 35 22 17 92 28 10 74 52]


##**Array Attributes**

In [40]:
vector = np.array([10, 20, 30, 40, 50])

print("Vector:")
print(vector)
print("Shape :", vector.shape)
print("Dimensions (ndim):", vector.ndim)
print("Data Type (dtype):", vector.dtype)
print("Total Elements (size):", vector.size)  # Vector Attributes

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)
print("Shape :", matrix.shape)
print("Dimensions (ndim):", matrix.ndim)
print("Data Type (dtype):", matrix.dtype)
print("Total Elements (size):", matrix.size) # Array/Matrix Attributes

tensor = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Tensor:")
print(tensor)
print("Shape :", tensor.shape)
print("Dimensions (ndim):", tensor.ndim)
print("Data Type (dtype):", tensor.dtype)
print("Total Elements (size):", tensor.size) # 3D Attributes

Vector:
[10 20 30 40 50]
Shape : (5,)
Dimensions (ndim): 1
Data Type (dtype): int64
Total Elements (size): 5
Matrix:
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Dimensions (ndim): 2
Data Type (dtype): int64
Total Elements (size): 6
3D Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape : (2, 2, 3)
Dimensions (ndim): 3
Data Type (dtype): int64
Total Elements (size): 12


## **Indexing and Slicing**

In [41]:
a = np.arange(20)
print(a[3])
print(a[5:10])
print(a[:7])
print(a[-1])   # Array Indexing

matrix = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
print(matrix[0])
print(matrix[:,2])
print(matrix[1:])
print(matrix[0:2,1:])  # Matrix Indexing

3
[5 6 7 8 9]
[0 1 2 3 4 5 6]
19
[1 2 3]
[3 6 9]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


## **Mathematical Operations**

In [42]:
salary = np.array([25000, 30000, 50000])

# 1. 10% raise
raise_salary = salary * 1.10

# 2. Tax deduction (10%)
tax = salary * 0.10

# 3. Monthly salary
monthly_salary = salary / 12

print("Original Salary:", salary)
print("Salary after 10% Raise:", raise_salary)
print("10% Tax Deduction:", tax)
print("Monthly Salary:", monthly_salary)

Original Salary: [25000 30000 50000]
Salary after 10% Raise: [27500. 33000. 55000.]
10% Tax Deduction: [2500. 3000. 5000.]
Monthly Salary: [2083.33333333 2500.         4166.66666667]


## **NumPy Vectorization**

In [43]:
#Regular Python Loop
n = 10_000_000
a = list(range(n))
b = list(range(n))
start = time.time()
c = [a[i] + b[i] for i in range(n)]
end = time.time()
print('Python loop time:', end - start)

#NumPy Python Loop
a = np.arange(n)
b = np.arange(n)
start = time.time()
c = a + b
end = time.time()
print('NumPy vectorized time:', end - start)

Python loop time: 1.1382520198822021
NumPy vectorized time: 0.1889946460723877


## **Broadcasting**

In [49]:
marks = np.array([
[45,27],
[38,41]
])
bonus = 5
marks_bonus = marks + bonus
percentage = (marks_bonus / 50) * 100

print("Original Marks:")
print(marks)

print("\nAfter Adding Bonus:")
print(marks_bonus)

print("\nPercentage:")
print(percentage)

Original Marks:
[[45 27]
 [38 41]]

After Adding Bonus:
[[50 32]
 [43 46]]

Percentage:
[[100.  64.]
 [ 86.  92.]]


## **Aggregation Functions**

In [53]:
salary = np.random.randint(10000, 50001, 10)
salary_n = np.round(salary / 500) * 500

print("Original:", salary)
print("Rounded to 500:", salary_n.astype(int))

print(np.sum(salary_n)) # Sum
print(np.mean(salary_n)) # Mean
print(np.median(salary_n)) # Median
print(np.std(salary_n)) # Standard Deviation
print(np.var(salary_n)) # Variance
print(np.min(salary_n)) # Minimum
print(np.max(salary_n)) #Maximum

Original: [45554 49210 38311 28154 13795 11648 41911 47548 21775 16323]
Rounded to 500: [45500 49000 38500 28000 14000 11500 42000 47500 22000 16500]
314500.0
31450.0
33250.0
13968.62555872982
195122500.0
11500.0
49000.0


## **Matrix Multiplication**

In [56]:
A = np.array([
[1,2],
[3,4]
])

B = np.array([
[5,6],
[7,8]
])

print(A+B)
print(np.dot(A,B))
print(A.T)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## **Linear Algebra**

In [57]:
# Create a square matrix
A = np.array([
    [4, 2],
    [1, 3]
])

print("Matrix A:")
print(A)
det = np.linalg.det(A)

print("Determinant:")
print(det)
inverse = np.linalg.inv(A)

print("Inverse:")
print(inverse)
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]
Determinant:
10.000000000000002
Inverse:
[[ 0.3 -0.2]
 [-0.1  0.4]]
Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
